version: 0.2

phases:
  pre_build:
    commands:
#      - echo "Getting base AMI"
#      - aws ec2 describe-images --owners self --filters "Name=tag:Name,Values=Prod-CIS-Latest-AMZN*" --query 'Images[*].{ImageId:ImageId,CreationDate:CreationDate}' --output text|sort|tail -1|awk '{print $2}' > ami_id.txt
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && unzip packer.zip
      - echo "Validating Packer template"
      - ./packer validate eks-worker-al2.json
  build:
    commands:
      # EKS K8s 1.11  # -var source_ami_owners=$AWS_ACCOUNT_ID -var source_ami_filter_name='Prod-CIS-Latest-AMZN-*'
      - ./packer build -var aws_region=${AWS_REGION} -var kubernetes_version=1.11 -var binary_bucket_path=1.11.9/2019-03-27/bin/linux/amd64 eks-worker-al2.json | tee build-eks-1.11.log
      # EKS K8s 1.12
      - ./packer build -var aws_region=${AWS_REGION} -var kubernetes_version=1.12 -var binary_bucket_path=1.12.7/2019-03-27/bin/linux/amd64 eks-worker-al2.json | tee build-eks-1.12.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build-eks-1.11.log | cut -d' ' -f2 > ami_id-eks-1.11.txt
      - egrep "${AWS_REGION}\:\sami\-" build-eks-1.12.log | cut -d' ' -f2 > ami_id-eks-1.12.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id-eks-1.11.txt || exit 1
      - test -s ami_id-eks-1.12.txt || exit 1
      - cp ami_builder_event.json ami_builder_event-1.11.json
      - cp ami_builder_event.json ami_builder_event-1.12.json
      - sed -i.bak "s/<<Version>>/1.11/g" ami_builder_event-1.11.json
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id-eks-1.11.txt)/g" ami_builder_event-1.11.json
      - aws events put-events --entries file://ami_builder_event-1.11.json
      - sed -i.bak "s/<<Version>>/1.12/g" ami_builder_event-1.12.json
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id-eks-1.12.txt)/g" ami_builder_event-1.12.json
      - aws events put-events --entries file://ami_builder_event-1.12.json
      - echo "build completed on `date`"
artifacts:
  files:
    - ami_builder_event-1.11.json
    - ami_builder_event-1.12.json
    - build.log
    - build-eks-1.11.log
    - build-eks-1.12.log
  discard-paths: yes
